blog/urls.py
from django.urls import path
from . import views
app_name = 'blog' #имя приложения

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
     #URL страницы отображения всех постов
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'), 
    #формируем URL страницы поста 
    path('<int:post_id>/share/', views.post_share, name='post_share') 
    #формируем URl для поста которым нужно поделиться
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models
from django.utils import timezone #импортируем модуль для отображения времени прямо сейчас
from django.contrib.auth.models import User #импортируем модель для определения автора(зарегистрировавшихся пользователей)
from django.urls import reverse #импортируем функцию формирования URL постов
# Create your models here.
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES =( #tuple с вариантами, Опубликован пост или Не опубликован
        ('draft', 'Draft'),
        ('published', 'Published')
    )
    title = models.CharField(max_length=250, verbose_name='Заголовок')
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts') #поле определя автора из зарегистрированных пользователей
    publish = models.DateTimeField(default=timezone.now) #
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta: #класс для отображения статей с фильтром (сначала новые)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-publish',)

    def __str__(self):
        return self.title #Корректное отображение названия модели

    def get_absolute_url(self): #формирование URL для страницы поста
        return reverse('blog:post_detail', args=[self.publish.year, #формируем через функцию reverse
            self.publish.month, self.publish.day, self.slug]) #аргументами являются название приложения : вьюха отображения args=[обращаемся через поле publish к необходимым полям для формирования URl]
    
    

class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Комментарии'
        verbose_name_plural = 'Комментарии'
        ordering = ('created', )

    def __str__(self):
        return 'Comment by {} on '.format(self.name, self.post)
    


    

blog/forms.py
from django import forms #импортируем класс forms
from .models import Comments





class EmailPostForm(forms.Form): 
    name = forms.CharField(max_length=25) # текстовое поле имя 
    email = forms.EmailField() #поле с мылом отправителя
    to = forms.EmailField() # поле с мылом получателя
    comments = forms.CharField(required=False, widget=forms.Textarea) #поле с комментарием по необходимости (не обязательное поле)


class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView #импорт класса для отображения списка объектов (постов) со встроенным пагинатором
from .forms import EmailPostForm, CommentsForm #импортируем форму из файла forms.py 
from django.core.mail import send_mail #импортируем функцию отправки сообщения на почту
from taggit.models import Tag
from django.db.models import Count






def post_detail(request, year, month, day, post): #вьюха отображения страницы поста
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day) #обозначаем переменную получающую опубликованный пост из модели Post, атрибуты прнимают значения года месяца и дня для фильтрации и формирования URL поста
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentsForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
        return render(request, 'blog/post/post_detail.html', {'post' : post, 'new_comment' : new_comment, 'comments' : comments, 'comment_form' :  comment_form})
    else:
        comment_form = CommentsForm()
    
    post_tag_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tag_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    context = {
        'post' : post,
        'new_comment' : new_comment,
        'comments' : comments,
        'comment_form' :  comment_form,
        'similar_posts' : similar_posts
        }
    return render(request, 'blog/post/post_detail.html', context) #возвращает данные определенного поста и отображает в шаблоне html




def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/post_list.html', {'page': page, 'posts': posts, 'tag' : tag})




class PostListView(ListView): #класс для вывода всех опубликованных постов из модели Post  
    queryset = Post.published.all() #получаем все посты через queryset запрос
    context_object_name = 'posts' #обозначаем контекст для последующей итерации в шаблоне
    paginate_by = 1 # устанавливаем колличество постов на 1 странице для реализации пагинации
    template_name = 'blog/post/post_list.html' #называем шаблон в который будем выводить полученные данные




def post_share(request, post_id): #функция отправки поста на почту

    post = get_object_or_404(Post, id=post_id,status='published')# Получение статьи по идентификатору.
    sent = False #переменная с исходным значением False для последующей реализации отображения в шаблоне успешной отправки
    if request.method == 'POST': #проверка метода запроса

        form = EmailPostForm(request.POST) # инициализируем экземпляр класса EmailPostForm() 
        if form.is_valid():
            # Если Все поля формы прошли валидацию выполняем отправку.
            cd = form.cleaned_data #метод clean_data возвращает словарь с данными из формы
            # Отправка электронной почты.
            post_url = request.build_absolute_uri(post.get_absolute_url()) # формируем полный URL адрес поста
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title) # Тема сообщения
            message = 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments']) # Тело сообщения
            send_mail(subject, message, 'uxui.des@gmail.com', [cd['to']]) #отправка сообщения обязательные аргумент : тема, тело, мыло отправителя , кому отправляется 
            sent = True #перезаписываем переменную при успешной отправке
            return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent}) #выводим сообщение об успешно отправке Email
    else:
        form = EmailPostForm() 
        return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})#выводим форму с указанием ошибок для исправления

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    
    {% endblock title %}
</head>
<body>
    {% block content %}

    {% endblock content %}
</body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
<span class="step-links">
{% if page.has_previous %}
<a href="?page={{page.previous_page_number}}">Previous</a>
{% endif %}
<span class="current">
Page {{ page.number }} of {{ page.paginator.num_pages }}.
</span>
{% if page.has_next %}
<a href="?page={{ page.next_page_number }}">Next</a>
{% endif %}
</span>
</div>

blog/templates/blog/post/post_detail.html
{% extends 'blog/base.html' %}



{% block title %}

{% endblock title %}



{% block content %}
<h2>

    {{ post.title }}

</h2>
<b> Теги: #{{ post.tags.all|join:"," }}</b>


<p>
    {{ post.body|linebreaks }}

</p>

<b>
    {{ post.author }}

</b>
<i>
    {{ post.publish }}
</i>
<a href="{% url "blog:post_share" post.id %}">Share</a>

{% with comments.count as total_comments %}

<h2> {{ total_comments }} comment{{ total_comments|pluralize }}</h2>

{% endwith %}



{% for comment in comments %}

<div class="comment">

    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
        {{ comment.created }}
    </p>
{{ comment.body|linebreaks }}

</div>

{% empty %}
    <p>There are no comments yet.</p>
{% endfor %}
{% if new_comment %}
<h3>
Ваш комментраий добавлен
</h3>

{% endif %}
<form action="" method="POST">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Add comment">

</form>
{% for post in similar_posts %}
<div>
<b>{{ post.title }}</b> <br>
{{ post.body }} <br>
{{ post.author }} <br>
</div>
{% endfor %}
{% endblock content %}

blog/templates/blog/post/post_list.html
{% extends 'blog/base.html' %}


{% block title %}
123
{% endblock title %}


{% block content %}


{% for post in posts %}
{% if tag %}
    <h2>Posts tagget: {{ tag.name }}</h2>
{% endif %}
{% for tag in post.tags.all %}
<a href="{% url "blog:post_list_by_tag" tag.slug%}">{{ tag.name }}</a>
{% endfor %}
<h2>
    <a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
</h2>
<p>{{ post.body|truncatewords:5|linebreaks }}</p>
<p>Published: {{ post.publish }}  by {{ post.author }}</p>


{% endfor %}

{% include 'blog/pagination.html' with page=posts %}

{% endblock content %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}
{% endblock title %}

{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>{{ post.title }} was successfully sent to {{ form.cleaned_data.to }}</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send mail">
</form>
{% endif %}
{% endblock content %}